### ISSUE TITLE
Fixes to GWAS-General

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#112]
Editing this to reflect that it's been broken out into many issues and is now an epic. The associated issues are tagged with GWAS

**Comment by ACharbonneau** [comment]
# setting up AWS page 
- moved to https://github.com/nih-cfde/training-and-engagement/issues/123 
      a t2.micro instance for Ubuntu Server 20.04 LTS (HVM), SSD Volume Type - ami-0d57c0143330e1fa7 (64-bit x86) / ami-05f126563b93d66c6 (64-bit Arm) cannot be launched without configuring a VPC if you are in US east (N. Virgina) us-east-1. 
![image](https://user-images.githubusercontent.com/1719360/88831248-1627d000-d19d-11ea-8bef-851157e4d8d0.png)
Need to tell uses a specific region to use. us-east-1, us-west-1 and us-west-2 all seem to have the machine config you picked. I would pick *one* of those and tell your user to just use that one rather than give them options.
- key pairs.
        -  [x] Users should *not* be creating new key pairs every time they do something in amazon. They're re-useable. So, the instructions should say something like "if you already have a key pair" and "if you don't have a key pair" and have instructions for both
        -  [x] The instructions you have do say 'save the pem to your desktop', but it's buried in a paragraph under an image instead of being a step. When a mac user (which is your expected user) hits "Download Key Pair" it is automatically downloaded to "Downloads" by default. If you're expecting the user to move it, that should be it's own step. I completely missed it.
- [x] Last line is "You have now successfully launched your AWS instance. DO NOT CLOSE THIS PAGE YET." I honestly don't now which page is "THIS PAGE". The tutorial? The AWS management page? I would make this less yelly, and more tell me what I actually need (and how to get back to it if I misunderstood and did close it)

**Comment by ACharbonneau** [comment]
# Accessing_aws page

- [x] Much, much later, in download the data, you have us download to our desktops and upload to AWS in a way that is going to be super error-prone:

> $ scp -i ~/Desktop/amazon.pem path/to/file/pruned_coatColor_maf_geno.vcf.gz ubuntu@ec2-???-???-???-???.compute-1.amazonaws.com:~/GWAS/.
> $ gunzip pruned_coatColor_maf_geno.vcf.gz #unzip the vcf.
> $ scp -i ~/Desktop/amazon.pem path/to/file/coatColor.pheno ubuntu@ec2-???-???-???-???.compute-1.amazonaws.com:~/GWAS/.

It would be much simpler if in this section you re-structured to have the user do something like:
- make a folder for this lesson locally
- download the pem
- move the pem to that folder
- cd to that folder
- chmod the pem
- download the data files they need now, while you have them in the right place
- then log into AWS (using the command you described, and point out that if they have trouble, they find in a copy/paste in 'Connect'
- then do a very simple thing in AWS: ls and show them nothing is there
- then type exit
- NOW have them upload the data, the command is generic because they are already in the folder with the pem and the data
- log back into AWS (it's good to do it multiple times, so they learn the ssh)
- ls again. LOOK THERE'S STUFF NOW
- then move on to installs

This does a few things:
- It gives them a chance to practice logging in and out of AWS
- It demonstrates that logging in and out *does not kill the computer*, so they understand that they are still paying for it
- It gives a feeling of accomplishment. Something demonstrably happened, and it happened early in the lesson. They learned to move stuff to the cloud. Early wins keep learners motivated,
- It reduce the number of things your user needs to keep in their head all at once to participate. In the current set up, your asking them to understand that theres a cloud and a local, and what is in each, and to keep track of a whole bunch of unfamiliar files (pems, data they don't know, software) spread across those two locations, and across different places in those locations. Giving them ONE folder locally to work in and ONE folder on the cloud to work in will free up the mental cycles they need to follow along with the actual science part.


---

 - [x] "Start this tutorial by opening up a terminal window by searching (type cmd+space_bar) for "terminal" on your Mac." implies that I am now doing a new tutorial. Change to something like "To access AWS you need to open a terminal..."
- [ ] This sentence is super confusing: "Copy this name, connect to the cloud computer with ssh under the username ‘ubuntu’, as follows:" Especially since the very next thing you say to do is chmod a file that does not seem to have anything to do with that sentence. The flow of a tutorial should be "Our goal is X. To do X, we need Y. These are the steps of Y". What you have is "Do Y. Do Z. This is Y."
- [ ] what is chmod? why am I doing it? what are these letters?  In Amazon, once your instance is running if you click the 'connect' button, it gives you personalized to your instance instructions for logging into that instance:
![image](https://user-images.githubusercontent.com/1719360/88830054-6ef66900-d19b-11ea-93f8-5bec44757f46.png)
 Yours is different. Is it *functionally* different? If I don't already know chmod, I don't know. 
- [ ] Would be nice to have a bit here about how they can use the connect button to get that info. It's handy

- [ ] Your most common error on this page will be the chmod not working or the ssh call not working because the user didn't put their pem where you expect, or call it what you expect. That should be an error/tip. That if it's not working, make sure the path to your pem file is correct, and that they're using the name they typed in the box
- [ ] Second most common error will be people just copying `$ ssh -i ~/Desktop/amazon.pem ubuntu@ec2-???-???-???-???.compute-1.amazonaws.com` and not realizing they need to change it. It only tells me the actual instructions in the "important" box. The boxes should be supplemental info, not the actual instructions.
- [ ] You've also red circled the whole Public DNS part of the image without specifying *which part* they put after the `@`. You will absolutely have people try to log in as `ubuntu@Public DNS: ec2-52-87-216-232.compute-1.amazonaws.com`
- [x] pedantic quibble "The authenticity of host 'ecc2-???-???-???-???.compute-1.amazonaws.com (3.129.57.169)' can't be established...." is not an error. It is the network asking to to explicitly acknowledge that it is connecting to the correct computer. I will always happen the first time you connect, and will not happen after that, because you only have to agree the first time. I would change this to a "tip" and add a bit more explanation. 
- [ ] The image of the yellow terminal is very hard to see. At the very least it could be cropped to much closer to the text

**Comment by ACharbonneau** [comment]
# What is PLINK

- [ ] In general, user experience surveys tell us that forcing people to fail makes them frustrated and less likely to finish/participate in the tutorial. We know that for "AMI whichever, in zone whatever, with a t2 or whatever" *exactly* what is already installed on that config. If wget and unzip aren't those things, we should have those get installed first, not have them try, get an error message they don't understand and *then* see that there's an error box in the tutorial. Error boxes should be for things we know occasionally happen, or for common mistakes, not for expected behavior. If it really *does* seem random...like if you had some installed bur marisa didn't...that's probably that you were in Ohio but she was in Oregon, or whatever. So. Choose one zone/AMI/size that our tutorial uses. See what that environment is. Set up the tutorial around that environment. Then, make the error box say something like "if wget or whatever aren't installed, that means you set up the wrong config." and tell them how to go back and get the right one. 
- [ ] For the two installs...why are we using two different package managers? And without any explanation of what those commands do/why they're installing brew. Do we ever use brew again? Can we just use apt-get? Or just use brew? And let's have at least a one line explanation about package managers.
- [ ] My version I've ended up with doesn't even have ruby installed so I can't install brew anyway without installing ruby. 
- [ ] There's so much sudo in here. We should not be using super user to download things and unzip them. You should only use sudo when you *have* to, it's pretty dangerous to just sudo everything. Also, we should have an explanation to the user (short is fine) the first time we use sudo to tell them why we use it, and that we shouldn't use it unless we have to. _I figured it out. It's because you were installing plink in bin. That is unnecessary. You can add any folder to PATH._


- [ ] A good way to have the user check to make sure the install worked is to use which `which plink` will only give an answer if the program has been successfully added to PATH.

**Comment by ACharbonneau** [comment]
# Install VFC tools

- [ ] Your first command only works *after* your second command. You should have users do `sudo apt-get update` *as their very first command*, when they're doing PLINK
>ubuntu@ip-172-31-33-127:~/vcftools$ sudo apt-get install autoconf autogen
>Reading package lists... Done
>Building dependency tree
>Reading state information... Done
>E: Unable to locate package autogen
- [ ] Why cd into VCF tools? Oh. I see. So. All of this apt-get stuff can happen in any folder, it just installs it to the system. Lets do all these installs with the wget, etc installs and not in the middle of VCF.
- [ ] Is there a reason we're not just doing all of these installs on one line?? Do they actually have to be installed in four chunks? And why are we updating apt-get again? Why do we install autoconf and pkg-config twice?
- curl was already installed on my instance.

**Comment by ACharbonneau** [comment]
# Install R

- [ ] We have run `apt-get update` so many times at this point. It doesn't necessarily hurt anything to run it a lot, but if I don't know what it does, I'm going to assume from this tutorial that it's the first step of literally every unix operation :)

**Comment by ACharbonneau** [comment]
# Download the data

- [ ] `wget` is not installed on macs by default. Since this is a mac-centric lesson, you can't have people use wget unless you teach them to install it locally. Generally, you don't want to make them install stuff locally, it's much more error prone than AWS. And, with AWS if they ruin it they can kill the instance and start over...if they break their local machine...its not good. Ask me about the time one of the ANGUS instructors accidentally made someone delete their local operating system. You should be using curl. `curl -LO` will download the output using the name on the server, and follow any symbolic links it needs to
- See the accessing aws comment box for more on rearranging this section
- [ ] you need to explain what SCP is and how they know this is how the command looks. Otherwise they will never be able to do this with their own data
- [ ] why gunzip? before we used unzip.
- [ ] Also, this code can't possibly be right??
> $ scp -i ~/Desktop/amazon.pem path/to/file/pruned_coatColor_maf_geno.vcf.gz ubuntu@ec2-???-???-???-???.compute-1.amazonaws.com:~/GWAS/.
> $ gunzip pruned_coatColor_maf_geno.vcf.gz #unzip the vcf.
> $ scp -i ~/Desktop/amazon.pem path/to/file/coatColor.pheno ubuntu@ec2-???-???-???-???.compute-1.amazonaws.com:~/GWAS/.

I'm in my local machine. I scp my file up to aws...then unzip it locally...then scp up the next one? Why would I unzip this file on my laptop??

**Comment by ACharbonneau** [comment]
# Analyze

> In order to specify the minor allele as the reference allele for PLINK

 - [ ] Why do I want to specify minor alleles?  

- [ ] So. There are certainly times where you don't want to explain all the code. AWK is absolutely one of those times. We aren't here to teach people AWK, and we don't have the 20 years it would take to do it. So that's fine. But, it's still best not to just drop complex code on people with no explanation at all. A couple sentences about what this code philosophically does, a throwaway about how learning AWK is a thing for another day, and a link to a nice AWK page should be here. Personally, I always link to grymoire for AWK and SED, because he actually does a pretty good job of making them approachable, and his writing style is really close to mine, so it fits really well in my tutorials [awk](https://www.grymoire.com/Unix/Awk.html), [sed](https://www.grymoire.com/Unix/Sed.html) 
- The plink note is good and helpful :)
- [ ] What does `Test value is [yellow] and missing value is [-9]` and `53 of 53 individuals assigned to 2 cluster(s)` mean?
- [ ] I would not just assume that people know how to quit `less` here
- [ ] I think it's okay to have a very basic tutorial like this that doesn't show all the options, but I think that a second tutorial that *does* show how to exclude SNPs and individuals would be very, very helpful. Those are extremely common things to need to do, and no one with real data would be able to do a GWAS without those steps, so adding them gives the user the ability to *practically* apply these new skills. 
- As an aside, the fact that you have said this is the most simple tutorial, and are not showing options underscores that the audience you're aiming at is *newbies*, so everything needs the amount of context and info that you have for the GWAS interpretation stuff here.

**Comment by ACharbonneau** [comment]
# Manhattan Plots

- [ ] More installs? We're almost to the exciting payoff of this tutorial! Don't ruin the flow with breaking to watch things install again. Install everything at the begining, where you can talk about install stuff all at once. And give them an overview of "we're installing this stuff, they do these steps, and that makes a pipeline" You do the talk while the installs run forever.
- [ ] another apt-get update
- [ ] the running the plot function code just doesn't work. I had to copy it all out and make it a single line in a text editor to make it function. It looks like this rscript can't accept `/` line breaks 
- [ ] "The output should look like this:" As long as you give it a valid data file, you get exactly that output regardless of whether the program works or not. This should get changed to an `ls -lthr`, which will show the last file made, and it's size. So, the user should check to see that they have a 34k file called coatColor_man.bmp
- [ ] for visualization, unless you have a reason for them to download all those files, switch it to *just* download the bmp and make your note about how to change it to download everything. Otherwise you are likely to crash your classroom internet connection. 
- [ ]  halptypes 
- [ ] Manhatten plots

**Comment by ACharbonneau** [comment]
# Terminate

- [ ] important should be first, not last. People do the instructions *THEN* read the notes while they wait for a thing to happen. They *will* just delete it without looking to see that's potentially bad.

**Comment by ACharbonneau** [comment]
# Overall comments/issues

- [x] You have made very nice copy/pasteable commands...but they don't work. When I click the copy button I get `$ chmod og-rwx ~/Desktop/amazon.pem` *including the `$` so the user can't actually use them. 
- [x] In some of the copy/pasteable command boxes the commands end in a period...like a sentence. That will really break things when people use it, and since period is a wildcard, might completely destroy their computers depending on the code you put before it. 
- [x] even if it's just a sentence, you should always tell your user what every new command is the first time you use it. There are thousands of unix commands, and a lot of them do very similar things. You can't assume that one you use frequently is one that everyone uses frequently. To paraphrase a quote from @ctb: I've been coding UNIX for 25 years, but every time I go to a workshop I learn a new command.
- [ ] A lot of the stuff in here doesn't have obvious motivation. Why should I assign alternate alleles? Why do I want to calculate missingness rates? Why am I ignoring sex? Why am I installing qqman? What is ghostscript? Why would I do any of this actually? 
- [ ] Think about your audience. They do not remotely care about dog genetics. They want to learn how to run a GWAS on *their own data*. Does this tutorial give them the information they need to do that? It works. It gives me this plot at the end. But if I give, say, Jose or Saranya a new set of files to run a GWAS on...could they do it?

**Comment by ACharbonneau** [comment]
# Asides about training

- The connect button is good for testing things AND for people who's terminal doesn't work/are on windows. If you select 'EC2 Instance Connect' 
![image](https://user-images.githubusercontent.com/1719360/88849695-3f098e80-d1b8-11ea-94d0-8293f7a65ea7.png)

it will launch a full working terminal in your browser:
![image](https://user-images.githubusercontent.com/1719360/88849754-547eb880-d1b8-11ea-8e49-55833873b6d9.png)

If it launches the box, but doesn't have the terminal in it, then there is a connection/security issue (like I had with the VPC thing). If it launches and has a working terminal, then the problem is to do with the users terminal (they're misspelling/using the wrong path to their pem) or the users location (they're connecting using an internet connection that blocks ssh. Happens in lots of airports, schools, etc)

**Comment by abhijna** [comment]
This got split into smaller issues and got done for oct release.
