### ISSUE TITLE
add all the people to the CP mailing list

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#186]
contact list is here:
https://docs.google.com/spreadsheets/d/1niqenLvLLN38Tfz2IXOaKum4Bo0N2m0HxM33X3E2pf8/edit#gid=0

NIH may be updating it, and we don't want to announce dates until some things have happened so wait on this until some sort of signal please

**Comment by jeremywalter** [comment]
Mailing list issues:

Current set-up:
**Potential Problems**
Everyone is added to #general (cannot be changed -- is this okay?)
Everyone is added to slack (can be turned off)
**Advantage**
Billing established, incurs no extra expense

**Tasks**
- [ ] Copy current general members to a 'CFDE Member' Subgroup (for funded members) 

- [ ] Create new mailing list for CFDE Member Subgroup (for funded members)

- [ ] Turn off slack automation

- [ ] Add CP participants to CrossPollination group (they will also be automatically become member of general and gain access to #general mailing list)

- [ ] Create CP Calendar for CrossPollination sub-group

**Alternative**
Use newly created group: https://groups.io/g/CrossPollinationEvents
Advantages: separate and independent from main CFDE group, calendar already built, slack integration possible
Disadvantages: new account needs to be bankrolled immediately for functionality

**Comment by ctb** [comment]
> Mailing list issues:
> 
> Current set-up:
> **Potential Problems**
> Everyone is added to #general (cannot be changed -- is this okay?)

you mean main? no, alas. On most of my groups.io lists, I never use main@.

> **Tasks**
> 
>     * [ ]  Copy current general members to a 'CFDE Member' Subgroup (for funded members)

It's not so much "copy" as "add"; happy to show you interface for dib-lab.
 
> **Alternative**
> Use newly created group: https://groups.io/g/CrossPollinationEvents
> Advantages: separate and independent from main CFDE group, calendar already built, slack integration possible
> Disadvantages: new account needs to be bankrolled immediately for functionality

I think either one can work, and the cost of a new list is minimal.

**Comment by jeremywalter** [comment]
Though my descriptions might have been off vocabulary-wise, I do believe I got the workflow (tasks) more or less right. I would really prefer to fire up a new group for the duration of the CP events just to keep things tidy and separate and give us some better integrations that we could use for the CP (such as automated Slack adds). The question then becomes: can we do this _today_ (Wednesday, September 16) so I can build and deploy everything.

**Comment by ACharbonneau** [comment]
I want the emails sent today (Wednesday) if at all possible. I think we've got enough set up to make it go? We can finalize via slack

**Comment by ACharbonneau** [comment]
actually, NIH hasn't looked at contacts yet. lets get the rest set up today tho

**Comment by jeremywalter** [comment]
Groups.io is set up, calendared, and ready to take on approved mailing lists.
https://groups.io/g/CrossPollinationEvents

**Comment by jeremywalter** [comment]
A combined list of Master + CFDE groups.io members will be added to the Cross Pollination groups.io today -- they will have access to the CP Calendar in groups.io.

**Comment by jeremywalter** [comment]
mailing list set to launch on Monday, will include groups.io notification and invitation to CP events

**Comment by ACharbonneau** [comment]
I got an email from wendy that they have added names to our list, so make sure we get the additions, but i think we're good to send

**Comment by jeremywalter** [comment]
https://docs.google.com/spreadsheets/d/1TIMAb7u8AfKMkn4mA7H610K0sJzWLORJw3JU_qj4_Yg/edit#gid=0

Mailling list populated from above list which is combined CFDE groups and master list.

**Comment by jeremywalter** [comment]
CP onboarding now included in general onboarding so that all new onboards will be automatically added to CP
