### ISSUE TITLE
June Site Release

### ISSUE THREAD

**Issue by raynamharris** [nih-cfde/training-and-engagement#532]
an issue for tracking things for the next planned release... June 2020

Extras
- [x] Contributing/ CoC, License files, Style Guide #542 
- [x] Style Guide and Release Plan #545 
- [x] updated actions and PR template #543 
- [x] Video recordings #540
- [x] fix typos #546 
- [x] Release Notes #549

Lessons
- [x] AWS #534
- [x] R #535 (merge this after unix)
- [x] Portal / DRS IDs #541
- [x] UNIX #537

**Comment by raynamharris** [comment]
all prs approved by at least 1 reviewer. this issue will be closed when https://github.com/nih-cfde/training-and-engagement/pull/549 is approved by 2 reviewers

**Comment by raynamharris** [comment]
done :) https://training.nih-cfde.org/en/latest/
